CREATE TABLE CLASSIFIED_AD (
    ID UUID PRIMARY KEY,
    OWNER_ID UUID NOT NULL,
    TITLE VARCHAR,
    TEXT VARCHAR,
    AMOUNT DECIMAL,
    CURRENCY_CODE VARCHAR(3),
    STATE VARCHAR NOT NULL,
    APPROVED_BY UUID
);
