CREATE TABLE USER_PROFILE (
    ID UUID PRIMARY KEY,
    FULL_NAME VARCHAR NOT NULL,
    DISPLAY_NAME VARCHAR NOT NULL,
    PHOTO_URL VARCHAR
);

CREATE TABLE CLASSIFIED_AD (
    ID UUID PRIMARY KEY,
    OWNER_ID UUID NOT NULL,
    TITLE VARCHAR,
    TEXT VARCHAR,
    AMOUNT DECIMAL,
    CURRENCY_CODE VARCHAR(3),
    STATE VARCHAR NOT NULL,
    APPROVED_BY UUID
);

CREATE TABLE PICTURE (
    ID UUID PRIMARY KEY,
    CLASSIFIED_AD_ID UUID,
    HEIGHT INT NOT NULL,
    WIDTH INT NOT NULL,
    LOCATION VARCHAR NOT NULL,
    "ORDER" INT NOT NULL,
    FOREIGN KEY (CLASSIFIED_AD_ID) REFERENCES CLASSIFIED_AD(ID)
);
